version: '2'
services:
  iptables:
    image: 4km3/set-iptables:latest
    privileged: true
    network_mode: host
    volumes:
      - ./entrypoint:/entrypoint
    restart: on-failure
    environment:
      - SET_IPTABLES_DEV=eth0
      - SET_IPTABLES_PROXY_PORT=3128
