#!/usr/bin/env sh

set -ex

# Example values for a transparent proxy
: "${SET_IPTABLES_DEV:=eth0}"
: "${SET_IPTABLES_PROXY_PORT:=3128}"
: "${SET_IPTABLES_PORTS:=80 443}"

for i in ${SET_IPTABLES_PORTS}; do
    iptables -D PREROUTING -t nat -i "${SET_IPTABLES_DEV}" -p tcp --dport $i -j REDIRECT --to-port "${SET_IPTABLES_PROXY_PORT}" || true
    iptables -A PREROUTING -t nat -i "${SET_IPTABLES_DEV}" -p tcp --dport $i -j REDIRECT --to-port "${SET_IPTABLES_PROXY_PORT}"
done
